### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by RosstheRoss** [UMN-EE4951W-Lamperski/pendulum-web#2]
## Middleware being used
https://www.passportjs.org/packages/passport-saml/ \
https://github.com/node-saml/passport-saml/issues/520 
## Guides from the University
https://it.umn.edu/services-technologies/self-help-guides/shibboleth
https://github.umn.edu/OIT-Identity-Management/iam-public/blob/master/attribute-map.xml

**Comment by RosstheRoss** [comment]
They still have not replied to me, which is infuriating.

**Comment by sama8** [comment]
If relevant -> [SAML Jackson](https://github.com/boxyhq/jackson)

**Comment by RosstheRoss** [comment]
I finally have access to the SAML system, now the fun part (testing) begins
